BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend ${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "sepolicy"
BBFILE_PRIORITY_sepolicy = "5"
BBFILE_PATTERN_sepolicy := "^${LAYERDIR}/"

# A similar recipe is provided by android_compat.
#  Use the version from meta-selinux instead.
BBMASK_append = "|.*/*/recipes-security/libselinux/"

PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls"
